project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('to_do_list_v2.urls')),
    path('accounts/', include('accounts.urls')),
]

to_do_list_v2/urls.py
from django.urls import path

from to_do_list_v2.views.errors_views import PageNotFound
from to_do_list_v2.views.projects_views import ProjectList, ProjectAddView, ProjectDetailView, ProjectEditView, \
    ProjectDeleteView, ProjectAddAuthor
from to_do_list_v2.views.tasks_views import TaskDetailView, TaskAddView, TaskEditView, TaskDeleteView

app_name = 'to_do_list'

urlpatterns = [
    path('page_not_found/', PageNotFound.as_view(), name="page_not_found"),

    path('', ProjectList.as_view(), name="home"),
    path('add_project/', ProjectAddView.as_view(), name="add_project"),
    path('project_detail/<int:pk>/', ProjectDetailView.as_view(), name="project_detail"),
    path('project_edit/<int:pk>/', ProjectEditView.as_view(), name="project_edit"),
    path('project_delete/<int:pk>/', ProjectDeleteView.as_view(), name="delete_project"),
    path('project_add_author/<int:pk>/', ProjectAddAuthor.as_view(), name="project_add_author"),

    path('project_detail/<int:pk>/task_add/', TaskAddView.as_view(), name="add_task"),
    path('task_detail/<int:pk>/', TaskDetailView.as_view(), name="task_detail"),
    path('task_edit/<int:pk>/', TaskEditView.as_view(), name="task_edit"),
    path('task_delete/<int:pk>/', TaskDeleteView.as_view(), name="delete_task"),
]

to_do_list_v2/models.py
from django.contrib.auth import get_user_model
from django.db import models


class TasksModel(models.Model):
    title = models.CharField(max_length=30, null=False, blank=False, verbose_name='Наименование')

    class Meta:
        db_table = 'TasksModel'
        verbose_name = 'Типы задач'
        verbose_name_plural = 'Типы задач'

    def __str__(self):
        return self.title


class StatusModel(models.Model):
    title = models.CharField(max_length=30, null=False, blank=False, verbose_name='Наименование')

    class Meta:
        db_table = 'StatusModel'
        verbose_name = 'Статусы'
        verbose_name_plural = 'Статусы'

    def __str__(self):
        return self.title


class ProjectModels(models.Model):
    summary = models.CharField(max_length=60, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=300, null=False, blank=False, verbose_name='Название')
    author = models.ManyToManyField(get_user_model(), related_name='projects',
                                    verbose_name='Автор ', blank=False)
    start_date = models.DateField(null=True, blank=False, verbose_name='Дата начала')
    end_date = models.DateField(blank=True, null=True, verbose_name='Дата окончания')

    class Meta:
        db_table = 'Project'
        verbose_name = 'Список проектов'
        verbose_name_plural = 'Список проектов'
        permissions = [
            ('change_author_projectmodels', 'Изменить авторов проекта')
        ]

    def __str__(self):
        return f'{self.summary}'


class ToDoListModels(models.Model):
    summary = models.CharField(max_length=60, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=300, null=True, blank=True, verbose_name='Название')
    status = models.ForeignKey('to_do_list_v2.StatusModel', related_name='statuses', verbose_name='Статусы',
                               on_delete=models.PROTECT)
    tasks = models.ManyToManyField('to_do_list_v2.TasksModel', related_name='tasks', verbose_name='Типы задач',
                                   blank=False)
    project = models.ForeignKey('to_do_list_v2.ProjectModels', related_name='projects', verbose_name='Проекты',
                                on_delete=models.PROTECT)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    class Meta:
        db_table = 'ToDoList'
        verbose_name = 'Список задач'
        verbose_name_plural = 'Список задач'

    def __str__(self):
        return f'{self.summary}'

to_do_list_v2/views/projects_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from to_do_list_v2.forms.task_form import SearchForm, ProjectForm, ProjectAddAuthorForm
from to_do_list_v2.models import ProjectModels, ToDoListModels


class ProjectList(ListView):
    model = ProjectModels
    template_name = 'projects/projects_list.html'
    context_object_name = 'projects'
    paginate_by = 5
    paginate_orphans = 1
    ordering = ("summary",)
    page_kwarg = 'page'

    def dispatch(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context["form"] = self.form
        if self.search_value:
            context["query"] = urlencode({'search': self.search_value})
            context["search_value"] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(summary__icontains=self.search_value) |
                                       Q(description__icontains=self.search_value))
        return queryset


class ProjectDetailView(DetailView):
    template_name = 'projects/detail_project.html'
    queryset = ProjectModels.objects.all()
    context_object_name = 'data'

    def dispatch(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        tasks = ToDoListModels.objects.all()
        context["form"] = self.form
        if self.search_value:
            context["query"] = urlencode({'search': self.search_value})
            context["search_value"] = self.search_value
            context['tasks'] = tasks.filter(project_id=self.object.pk).filter(Q(summary__icontains=self.search_value) |
                                                                              Q(description__icontains=self.search_value)).distinct()
        else:
            context['tasks'] = tasks.filter(project_id=self.object.pk).distinct()
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class ProjectAddView(PermissionRequiredMixin, CreateView):
    template_name = 'projects/add_project.html'
    form_class = ProjectForm
    permission_required = 'to_do_list_v2.add_projectmodels'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("to_do_list:page_not_found")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        project = form.save(commit=False)
        project.save()
        project.author.set([self.request.user.id], )
        form.save_m2m()
        return redirect("to_do_list:project_detail", pk=project.pk)

    def get_success_url(self):
        return reverse("to_do_list:project_detail", kwargs={"pk": self.object.pk})

    def has_permission(self):
        return super().has_permission()


class ProjectEditView(PermissionRequiredMixin, UpdateView):
    model = ProjectModels
    form_class = ProjectForm
    template_name = "projects/edit_project.html"
    permission_required = 'to_do_list_v2.change_projectmodels'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("to_do_list:page_not_found")
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("to_do_list:project_detail", kwargs={"pk": self.object.pk})

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().author.all()


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    model = ProjectModels
    template_name = "projects/delete_project.html"
    context_object_name = 'project'
    success_url = reverse_lazy("to_do_list:home")
    permission_required = 'to_do_list_v2.delete_projectmodels'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("to_do_list:page_not_found")
        return super().dispatch(request, *args, **kwargs)

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().author.all()


class ProjectAddAuthor(PermissionRequiredMixin, UpdateView):
    model = ProjectModels
    template_name = 'projects/add_project_author.html'
    form_class = ProjectAddAuthorForm
    permission_required = 'to_do_list_v2.change_author_projectmodels'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("to_do_list:page_not_found")
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("to_do_list:project_detail", kwargs={"pk": self.object.pk})

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().author.all()

templates/projects/add_project.html
{% extends 'base.html' %}
{% block title %}Добавление задачи{% endblock %}
{% block content %}
    <form action="" method="POST">
        {% include 'partial/form.html' %}
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
{% endblock %}

templates/projects/add_project_author.html
{% extends 'base.html' %}
{% block title %}Добавление задачи{% endblock %}
{% block content %}
    <form action="" method="POST">
        {% include 'partial/form.html' %}
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
{% endblock %}

templates/projects/delete_project.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Удаление задачи{% endblock %}
{% block content %}
    <div class="d-block">
        <p class="card-text">Вы точно хотите удалить проект:<span class="text-danger"> {{ project.summary }}</span>
        </p>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="btn-group" role="group">
            <button type="submit" name="delete" class="btn btn-danger" value="yes">Да</button>
        </div>
        <a class="btn btn-primary" href="{% url "to_do_list:home" %}">Нет</a>
    </form>
{% endblock %}

templates/projects/detail_project.html
{% extends 'base.html' %}
{% block title %}Детальный просмотр{% endblock %}
{% block link %}
    {% if user.is_authenticated %}
        {% if perms.to_do_list_v2.add_todolistmodels and request.user in data.author.all%}
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'to_do_list:add_task' data.id %}">Добавить
                        задачу</a>
                </li>
            </ul>
        {% endif %}
    {% endif %}
{% endblock %}
{% block content %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ data.summary }}</h5>
            <p class="card-text">{{ data.description }}</p>

            <p class="card-text">Участники:<strong>
                {% for author in data.author.all %}
                    {{ author }}{% if not forloop.last %},
                    {% endif %}
                {% endfor %}</strong></p>

            <p class="card-text">Дата старта проекта: {{ data.start_date|date:'Y-m-d' }}</p>
            <p class="card-text">Дата окончания старта: {{ data.end_date|date:'Y-m-d' }}</p>
            {% if user.is_authenticated %}
                {% if perms.to_do_list_v2.change_projectmodels and request.user in data.author.all %}
                    <a href="{% url 'to_do_list:project_edit' data.id %}" class="btn btn-primary">Изменить</a>
                {% endif %}
                {% if perms.to_do_list_v2.change_author_projectmodels and request.user in data.author.all %}
                    <a href="{% url 'to_do_list:project_add_author' data.id %}" class="btn btn-primary">Добавить
                        соавторов</a>
                {% endif %}
                {% if perms.to_do_list_v2.delete_projectmodels and request.user in data.author.all %}
                    <a href="{% url 'to_do_list:delete_project' data.id %}" class="btn btn-danger">Удалить</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        {% for list in tasks %}
            <div class="col-sm-2 mb-3 d-flex">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ list.summary }}</h5>
                        <p class="card-text">{{ list.description }}</p>
                        <div class="card_link">
                            <a href="{% url 'to_do_list:task_detail' list.id %}"
                               class="btn btn-primary stretched-link">Детальный
                                просмотр</a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <span>Создайте задачу</span>
        {% endfor %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}

    </div>
{% endblock %}

templates/projects/edit_project.html
{% extends 'base.html' %}
{% block title %}Изменение задачи{% endblock %}
{% block content %}
    <form action="" method="POST">
        {% include 'partial/form.html' %}
        <button type="submit" class="btn btn-primary">Изменить</button>
    </form>
{% endblock %}

templates/projects/projects_list.html
{% extends 'base.html' %}
{% block title %}Главная{% endblock %}
{% block search %}
    <form class="d-flex" role="search">
        <input class="form-control me-2" name="search" type="search" placeholder="Что ищем?" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Поиск</button>
    </form>
{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        {% for list in projects %}
            <div class="col-sm-2 mb-3 d-flex">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ list.summary }}</h5>
                        <p class="card-text">{{ list.description }}</p>
                        <div class="card_link">
                            <a href="{% url 'to_do_list:project_detail' list.id %}" class="btn btn-primary stretched-link">Детальный
                                просмотр</a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <span>Создайте задачу</span>
        {% endfor %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}

    </div>
{% endblock %}