accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('to_do_list_v2.urls')),
    path('accounts/', include('accounts.urls')),
]

to_do_list_v2/urls.py
from django.urls import path

from to_do_list_v2.views.errors_views import PageNotFound
from to_do_list_v2.views.projects_views import ProjectList, ProjectAddView, ProjectDetailView, ProjectEditView, \
    ProjectDeleteView, ProjectAddAuthor
from to_do_list_v2.views.tasks_views import TaskDetailView, TaskAddView, TaskEditView, TaskDeleteView

app_name = 'to_do_list'

urlpatterns = [
    path('page_not_found/', PageNotFound.as_view(), name="page_not_found"),

    path('', ProjectList.as_view(), name="home"),
    path('add_project/', ProjectAddView.as_view(), name="add_project"),
    path('project_detail/<int:pk>/', ProjectDetailView.as_view(), name="project_detail"),
    path('project_edit/<int:pk>/', ProjectEditView.as_view(), name="project_edit"),
    path('project_delete/<int:pk>/', ProjectDeleteView.as_view(), name="delete_project"),
    path('project_add_author/<int:pk>/', ProjectAddAuthor.as_view(), name="project_add_author"),

    path('project_detail/<int:pk>/task_add/', TaskAddView.as_view(), name="add_task"),
    path('task_detail/<int:pk>/', TaskDetailView.as_view(), name="task_detail"),
    path('task_edit/<int:pk>/', TaskEditView.as_view(), name="task_edit"),
    path('task_delete/<int:pk>/', TaskDeleteView.as_view(), name="delete_task"),
]

to_do_list_v2/views/errors_views.py
from django.views.generic import TemplateView


class PageNotFound(TemplateView):
    template_name = 'error.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['error'] = 'Такой страницы не существует'
        return context

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% block navbar %}
        {% include 'partial/navbar.html' %}
        {% block link %}
        {% endblock %}
        {% if user.is_authenticated %}
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{% url 'accounts:logout' %}?next={{ request.path }}">Выход</a>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{% url 'accounts:register' %}?next={{ request.path }}">Регистрация</a>
                </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{% url 'accounts:login' %}?next={{ request.path }}">Вход</a>
                </li>
            </ul>
        {% endif %}
        <div class="ms-auto">
            <form class="d-flex" role="search">
                <input class="form-control me-2" name="search" type="search" placeholder="Что ищем?"
                       aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Поиск</button>
            </form>
        </div>
        </div>
        </div>
        </nav>
    {% endblock %}

{% block content %}
{% endblock %}
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</html>

templates/error.html
{% extends 'base.html' %}
{% block title %}Изменение задачи{% endblock %}
{% block content %}
    <div class="card text-center">
        <div class="card-body">
            <h5 class="card-title">{{ error }}</h5>
            <a href="{% url 'to_do_list:home' %}" class="btn btn-primary">На главную</a>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
    <div class="row">
        {% for list in todolists %}
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ list.summary }}</h5>
                        <p class="card-text"><strong>
                            {% for task in list.tasks.all %}
                                {{ task.title }}{% if not forloop.last %},
                                {% endif %}
                            {% endfor %}:</strong> {{ list.status }}</p>
                        <a href="{% url 'task_detail' list.id %}" class="btn btn-primary">Детальный просмотр</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}