project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('to_do_list_v2.urls')),
    path('accounts/', include('accounts.urls')),
]

to_do_list_v2/urls.py
from django.urls import path

from to_do_list_v2.views.errors_views import PageNotFound
from to_do_list_v2.views.projects_views import ProjectList, ProjectAddView, ProjectDetailView, ProjectEditView, \
    ProjectDeleteView, ProjectAddAuthor
from to_do_list_v2.views.tasks_views import TaskDetailView, TaskAddView, TaskEditView, TaskDeleteView

app_name = 'to_do_list'

urlpatterns = [
    path('page_not_found/', PageNotFound.as_view(), name="page_not_found"),

    path('', ProjectList.as_view(), name="home"),
    path('add_project/', ProjectAddView.as_view(), name="add_project"),
    path('project_detail/<int:pk>/', ProjectDetailView.as_view(), name="project_detail"),
    path('project_edit/<int:pk>/', ProjectEditView.as_view(), name="project_edit"),
    path('project_delete/<int:pk>/', ProjectDeleteView.as_view(), name="delete_project"),
    path('project_add_author/<int:pk>/', ProjectAddAuthor.as_view(), name="project_add_author"),

    path('project_detail/<int:pk>/task_add/', TaskAddView.as_view(), name="add_task"),
    path('task_detail/<int:pk>/', TaskDetailView.as_view(), name="task_detail"),
    path('task_edit/<int:pk>/', TaskEditView.as_view(), name="task_edit"),
    path('task_delete/<int:pk>/', TaskDeleteView.as_view(), name="delete_task"),
]

to_do_list_v2/models.py
from django.contrib.auth import get_user_model
from django.db import models


class TasksModel(models.Model):
    title = models.CharField(max_length=30, null=False, blank=False, verbose_name='Наименование')

    class Meta:
        db_table = 'TasksModel'
        verbose_name = 'Типы задач'
        verbose_name_plural = 'Типы задач'

    def __str__(self):
        return self.title


class StatusModel(models.Model):
    title = models.CharField(max_length=30, null=False, blank=False, verbose_name='Наименование')

    class Meta:
        db_table = 'StatusModel'
        verbose_name = 'Статусы'
        verbose_name_plural = 'Статусы'

    def __str__(self):
        return self.title


class ProjectModels(models.Model):
    summary = models.CharField(max_length=60, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=300, null=False, blank=False, verbose_name='Название')
    author = models.ManyToManyField(get_user_model(), related_name='projects',
                                    verbose_name='Автор ', blank=False)
    start_date = models.DateField(null=True, blank=False, verbose_name='Дата начала')
    end_date = models.DateField(blank=True, null=True, verbose_name='Дата окончания')

    class Meta:
        db_table = 'Project'
        verbose_name = 'Список проектов'
        verbose_name_plural = 'Список проектов'
        permissions = [
            ('change_author_projectmodels', 'Изменить авторов проекта')
        ]

    def __str__(self):
        return f'{self.summary}'


class ToDoListModels(models.Model):
    summary = models.CharField(max_length=60, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=300, null=True, blank=True, verbose_name='Название')
    status = models.ForeignKey('to_do_list_v2.StatusModel', related_name='statuses', verbose_name='Статусы',
                               on_delete=models.PROTECT)
    tasks = models.ManyToManyField('to_do_list_v2.TasksModel', related_name='tasks', verbose_name='Типы задач',
                                   blank=False)
    project = models.ForeignKey('to_do_list_v2.ProjectModels', related_name='projects', verbose_name='Проекты',
                                on_delete=models.PROTECT)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    class Meta:
        db_table = 'ToDoList'
        verbose_name = 'Список задач'
        verbose_name_plural = 'Список задач'

    def __str__(self):
        return f'{self.summary}'

templates/partial/form.html
 {% csrf_token %}

        {% for field in form %}
            <div class="mb-3">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% for error in field.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}

templates/partial/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'to_do_list:home' %}">ToDoList</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if user.is_authenticated %}
                {% if perms.to_do_list_v2.add_projectmodels %}
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'to_do_list:add_project' %}">Добавить
                                проект</a>
                        </li>
                    </ul>
                {% endif %}
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <span class="nav-link active">Здравствуйте {{ request.user }}</span>
                    </li>
                </ul>
            {% endif %}

templates/partial/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li>
            <a class="page-link" href="?page=1">В начало</a>
        </li>
        <li class="page-item">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            {% else %}
                <span class="page-link disabled">Предыдущая</span>
            {% endif %}
        </li>
        {% for page in page_obj.paginator.page_range %}
            <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
        {% endfor %}
        <li class="page-item">
            {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
            {% else %}
                <span class="page-link disabled">Следующая</span>
            {% endif %}

        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">В конец</a>
        </li>
    </ul>
</nav>