project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('to_do_list_v2.urls')),
    path('accounts/', include('accounts.urls')),
]

to_do_list_v2/urls.py
from django.urls import path

from to_do_list_v2.views.errors_views import PageNotFound
from to_do_list_v2.views.projects_views import ProjectList, ProjectAddView, ProjectDetailView, ProjectEditView, \
    ProjectDeleteView, ProjectAddAuthor
from to_do_list_v2.views.tasks_views import TaskDetailView, TaskAddView, TaskEditView, TaskDeleteView

app_name = 'to_do_list'

urlpatterns = [
    path('page_not_found/', PageNotFound.as_view(), name="page_not_found"),

    path('', ProjectList.as_view(), name="home"),
    path('add_project/', ProjectAddView.as_view(), name="add_project"),
    path('project_detail/<int:pk>/', ProjectDetailView.as_view(), name="project_detail"),
    path('project_edit/<int:pk>/', ProjectEditView.as_view(), name="project_edit"),
    path('project_delete/<int:pk>/', ProjectDeleteView.as_view(), name="delete_project"),
    path('project_add_author/<int:pk>/', ProjectAddAuthor.as_view(), name="project_add_author"),

    path('project_detail/<int:pk>/task_add/', TaskAddView.as_view(), name="add_task"),
    path('task_detail/<int:pk>/', TaskDetailView.as_view(), name="task_detail"),
    path('task_edit/<int:pk>/', TaskEditView.as_view(), name="task_edit"),
    path('task_delete/<int:pk>/', TaskDeleteView.as_view(), name="delete_task"),
]

to_do_list_v2/models.py
from django.contrib.auth import get_user_model
from django.db import models


class TasksModel(models.Model):
    title = models.CharField(max_length=30, null=False, blank=False, verbose_name='Наименование')

    class Meta:
        db_table = 'TasksModel'
        verbose_name = 'Типы задач'
        verbose_name_plural = 'Типы задач'

    def __str__(self):
        return self.title


class StatusModel(models.Model):
    title = models.CharField(max_length=30, null=False, blank=False, verbose_name='Наименование')

    class Meta:
        db_table = 'StatusModel'
        verbose_name = 'Статусы'
        verbose_name_plural = 'Статусы'

    def __str__(self):
        return self.title


class ProjectModels(models.Model):
    summary = models.CharField(max_length=60, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=300, null=False, blank=False, verbose_name='Название')
    author = models.ManyToManyField(get_user_model(), related_name='projects',
                                    verbose_name='Автор ', blank=False)
    start_date = models.DateField(null=True, blank=False, verbose_name='Дата начала')
    end_date = models.DateField(blank=True, null=True, verbose_name='Дата окончания')

    class Meta:
        db_table = 'Project'
        verbose_name = 'Список проектов'
        verbose_name_plural = 'Список проектов'
        permissions = [
            ('change_author_projectmodels', 'Изменить авторов проекта')
        ]

    def __str__(self):
        return f'{self.summary}'


class ToDoListModels(models.Model):
    summary = models.CharField(max_length=60, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=300, null=True, blank=True, verbose_name='Название')
    status = models.ForeignKey('to_do_list_v2.StatusModel', related_name='statuses', verbose_name='Статусы',
                               on_delete=models.PROTECT)
    tasks = models.ManyToManyField('to_do_list_v2.TasksModel', related_name='tasks', verbose_name='Типы задач',
                                   blank=False)
    project = models.ForeignKey('to_do_list_v2.ProjectModels', related_name='projects', verbose_name='Проекты',
                                on_delete=models.PROTECT)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    class Meta:
        db_table = 'ToDoList'
        verbose_name = 'Список задач'
        verbose_name_plural = 'Список задач'

    def __str__(self):
        return f'{self.summary}'

to_do_list_v2/forms/task_form.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets

from to_do_list_v2.models import ToDoListModels, ProjectModels


class TaskForm(forms.ModelForm):
    class Meta:
        model = ToDoListModels
        fields = ['summary', 'description', 'status', 'tasks']
        widgets = {'summary': widgets.TextInput(attrs={'class': 'form-control'}),
                   'description': widgets.Textarea(attrs={'class': 'form-control'}),
                   'status': widgets.Select(attrs={'class': 'form-control'}),
                   'tasks': widgets.CheckboxSelectMultiple
                   }

    def clean_summary(self):
        summary = self.cleaned_data['summary']
        if len(summary) < 10:
            raise ValidationError('This field should be at least %(length)d symbols long!', code='too_short_summary',
                                  params={'length': 10})
        return summary

    def clean_description(self):
        description = self.cleaned_data['description']
        if len(description) < 20:
            raise ValidationError('This field should be at least %(length)d symbols long!',
                                  code='too_short_description',
                                  params={'length': 20})
        return description


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")


class ProjectForm(forms.ModelForm):
    class Meta:
        model = ProjectModels
        fields = ['summary', 'description', 'start_date', 'end_date']
        widgets = {'summary': widgets.TextInput(attrs={'class': 'form-control'}),
                   'description': widgets.Textarea(attrs={'class': 'form-control'}),
                   'start_date': widgets.DateInput(format='%Y-%m-%d', attrs={'class': 'form-control', 'type': 'date'}),
                   'end_date': widgets.DateInput(format='%Y-%m-%d', attrs={'class': 'form-control', 'type': 'date'})}


class ProjectAddAuthorForm(forms.ModelForm):
    class Meta:
        model = ProjectModels
        fields = ['author']
        widgets = {'author': widgets.SelectMultiple(attrs={'class': 'form-control'})}

to_do_list_v2/views/tasks_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from to_do_list_v2.forms.task_form import TaskForm
from to_do_list_v2.models import ToDoListModels, ProjectModels


class TaskDetailView(DetailView):
    template_name = 'tasks/detail_task.html'
    queryset = ToDoListModels.objects.all()
    context_object_name = 'data'


class TaskAddView(PermissionRequiredMixin, CreateView):
    template_name = 'tasks/add_task.html'
    form_class = TaskForm
    permission_required = 'to_do_list_v2.add_todolistmodels'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("to_do_list:page_not_found")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        project = get_object_or_404(ProjectModels, pk=self.kwargs.get("pk"))
        comment = form.save(commit=False)
        comment.project = project
        comment.save()
        form.save_m2m()
        return redirect("to_do_list:project_detail", pk=project.pk)

    def has_permission(self):
        project = get_object_or_404(ProjectModels, pk=self.kwargs.get("pk"))
        return super().has_permission() and self.request.user in project.author.all()


class TaskEditView(PermissionRequiredMixin, UpdateView):
    model = ToDoListModels
    form_class = TaskForm
    template_name = "tasks/edit_task.html"
    permission_required = 'to_do_list_v2.change_todolistmodels'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("to_do_list:page_not_found")
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("to_do_list:task_detail", kwargs={"pk": self.object.pk})

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().project.author.all()


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    model = ToDoListModels
    template_name = "tasks/delete_task.html"
    context_object_name = 'tasks'
    success_url = reverse_lazy("to_do_list:home")
    permission_required = 'to_do_list_v2.delete_todolistmodels'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("to_do_list:page_not_found")
        return super().dispatch(request, *args, **kwargs)

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().project.author.all()

templates/tasks/add_task.html
{% extends 'base.html' %}
{% block title %}Добавление задачи{% endblock %}
{% block content %}
    <form action="" method="POST">
        {% include 'partial/form.html' %}
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
{% endblock %}

templates/tasks/delete_task.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Удаление задачи{% endblock %}
{% block content %}
    <div class="d-block">
        <p class="card-text">Вы точно хотите удалить задачу:<span class="text-danger"> {{ tasks.summary }}</span>
        </p>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="btn-group" role="group">
            <button type="submit" name="delete" class="btn btn-danger" value="yes">Да</button>
        </div>
        <a class="btn btn-primary" href="{% url "to_do_list:home" %}">Нет</a>
    </form>
{% endblock %}

templates/tasks/detail_task.html
{% extends 'base.html' %}
{% block title %}Детальный просмотр{% endblock %}
{% block content %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ data.summary }}</h5>
            <p class="card-text">{{ data.description }}</p>
            <p class="card-text"><strong>
                {% for task in data.tasks.all %}
                    {{ task.title }}{% if not forloop.last %},
                    {% endif %}
                {% endfor %}:</strong> {{ data.status }}</p>
            <p class="card-text">Дата добавления: {{ data.create_date|date:'Y-m-d H:i' }}</p>
            <p class="card-text">Дата обновления: {{ data.update_date|date:'Y-m-d H:i' }}</p>
            {% if user.is_authenticated %}
                {% if perms.to_do_list_v2.change_todolistmodels and request.user in data.project.author.all %}
                    <a href="{% url 'to_do_list:task_edit' data.id %}" class="btn btn-primary">Изменить</a>
                {% endif %}
                {% if perms.to_do_list_v2.delete_todolistmodels and request.user in data.project.author.all %}
                    <a href="{% url 'to_do_list:delete_task' data.id %}" class="btn btn-danger">Удалить</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/tasks/edit_task.html
{% extends 'base.html' %}
{% block title %}Изменение задачи{% endblock %}
{% block content %}
    <form action="" method="POST">
        {% include 'partial/form.html' %}
        <button type="submit" class="btn btn-primary">Изменить</button>
    </form>
{% endblock %}